import type {
  Category,
  Brand,
  Product,
  Banner,
  Coupon,
  NotificationItem,
  Review,
  Order,
  Address,
} from "./types";

export const categories: Category[] = [
  { id: "cat-mob", slug: "mobiles", name: "Mobiles", icon: "Smartphone", order: 1, featured: true, image: "/img/cat-mobiles.svg",
    subcategories: [
      { id: "cat-mob-smart", slug: "smartphones", name: "Smartphones", parentId: "cat-mob", order: 1 },
      { id: "cat-mob-access", slug: "mobile-accessories", name: "Mobile Accessories", parentId: "cat-mob", order: 2 },
      { id: "cat-mob-tablet", slug: "tablets", name: "Tablets", parentId: "cat-mob", order: 3 },
      { id: "cat-mob-wear", slug: "wearables", name: "Smart Wearables", parentId: "cat-mob", order: 4 },
    ]
  },
  { id: "cat-elec", slug: "electronics", name: "Electronics", icon: "Cpu", order: 2, featured: true, image: "/img/cat-electronics.svg",
    subcategories: [
      { id: "cat-elec-tv", slug: "televisions", name: "Televisions", parentId: "cat-elec", order: 1 },
      { id: "cat-elec-audio", slug: "audio", name: "Audio & Headphones", parentId: "cat-elec", order: 2 },
      { id: "cat-elec-cam", slug: "cameras", name: "Cameras", parentId: "cat-elec", order: 3 },
      { id: "cat-elec-laptop", slug: "laptops", name: "Laptops", parentId: "cat-elec", order: 4 },
    ]
  },
  { id: "cat-fash", slug: "fashion", name: "Fashion", icon: "Shirt", order: 3, featured: true, image: "/img/cat-fashion.svg",
    subcategories: [
      { id: "cat-fash-men", slug: "mens-fashion", name: "Men", parentId: "cat-fash", order: 1 },
      { id: "cat-fash-women", slug: "womens-fashion", name: "Women", parentId: "cat-fash", order: 2 },
      { id: "cat-fash-kids", slug: "kids-fashion", name: "Kids", parentId: "cat-fash", order: 3 },
      { id: "cat-fash-footwear", slug: "footwear", name: "Footwear", parentId: "cat-fash", order: 4 },
    ]
  },
  { id: "cat-groc", slug: "grocery", name: "Grocery", icon: "Apple", order: 4, featured: true, image: "/img/cat-grocery.svg" },
  { id: "cat-beau", slug: "beauty", name: "Beauty", icon: "Sparkles", order: 5, featured: true, image: "/img/cat-beauty.svg" },
  { id: "cat-home", slug: "home-furniture", name: "Home & Furniture", icon: "Sofa", order: 6, image: "/img/cat-home.svg" },
  { id: "cat-app", slug: "appliances", name: "Appliances", icon: "WashingMachine", order: 7, image: "/img/cat-appliances.svg" },
  { id: "cat-sport", slug: "sports", name: "Sports", icon: "Dumbbell", order: 8, image: "/img/cat-sports.svg" },
  { id: "cat-books", slug: "books", name: "Books", icon: "Book", order: 9, image: "/img/cat-books.svg" },
  { id: "cat-toys", slug: "toys", name: "Toys", icon: "Blocks", order: 10, image: "/img/cat-toys.svg" },
  { id: "cat-auto", slug: "automotive", name: "Automotive", icon: "Car", order: 11, image: "/img/cat-auto.svg" },
  { id: "cat-acc", slug: "accessories", name: "Accessories", icon: "Watch", order: 12, image: "/img/cat-acc.svg" },
];

export const brands: Brand[] = [
  { id: "br-nova", slug: "novatech", name: "NovaTech" },
  { id: "br-aurora", slug: "aurora", name: "Aurora" },
  { id: "br-voltrix", slug: "voltrix", name: "Voltrix" },
  { id: "br-lumen", slug: "lumen", name: "Lumen" },
  { id: "br-vega", slug: "vega", name: "Vega" },
  { id: "br-saffron", slug: "saffronwear", name: "SaffronWear" },
  { id: "br-fresh", slug: "freshkart", name: "FreshKart" },
  { id: "br-zen", slug: "zenith", name: "Zenith" },
  { id: "br-vela", slug: "vela", name: "Vela" },
  { id: "br-roshni", slug: "roshni", name: "Roshni" },
  { id: "br-nirmaan", slug: "nirmaan", name: "Nirmaan" },
  { id: "br-dhruv", slug: "dhruv", name: "Dhruv" },
];

const img = (seed: number, w = 800, h = 800) =>
  `https://picsum.photos/seed/lvigs-${seed}/${w}/${h}`;

const productSeed = (i: number, p: Partial<Product>): Product => ({
  id: `pr-${i}`,
  slug: `product-${i}`,
  title: `Sample Product ${i}`,
  brand: "NovaTech",
  brandId: "br-nova",
  categoryId: "cat-mob",
  sellerId: "sel-1",
  sellerName: "LVIGS Official Store",
  description: "High quality product sourced directly from verified sellers with warranty.",
  highlights: ["Genuine product", "1 year warranty", "Easy returns"],
  specifications: [
    { label: "Brand", value: "NovaTech" },
    { label: "Model", value: `NT-${1000 + i}` },
    { label: "Warranty", value: "1 Year" },
    { label: "Country of Origin", value: "India" },
  ],
  rating: 4 + Math.random(),
  ratingCount: 200 + Math.floor(Math.random() * 5000),
  reviewCount: 150 + Math.floor(Math.random() * 3000),
  mrp: 9999,
  price: 4999,
  images: [img(i), img(i + 1), img(i + 2), img(i + 3)],
  stock: 100,
  deliveryCharge: 0,
  freeDelivery: true,
  fastDelivery: i % 3 === 0,
  tags: ["trending", "deal"],
  createdAt: new Date(Date.now() - i * 86400000).toISOString(),
  ...p,
});

export const products: Product[] = [
  productSeed(1, {
    slug: "novaphone-x9-pro",
    title: "NovaPhone X9 Pro 5G (256 GB)",
    brand: "NovaTech",
    brandId: "br-nova",
    categoryId: "cat-mob",
    subcategoryId: "cat-mob-smart",
    description: "Flagship-grade performance with the NovaCore G3 chip, 6.7\" AMOLED display, 50 MP triple camera and a 5000 mAh battery. Built for creators and gamers.",
    highlights: ["6.7\" AMOLED 120Hz", "50MP Triple Camera", "5000mAh, 80W fast charge", "NovaCore G3 chipset"],
    price: 34999, mrp: 54999,
    rating: 4.6, ratingCount: 8432, reviewCount: 5612,
    images: [img(101), img(102), img(103), img(104)],
    isBestseller: true, fastDelivery: true,
    attributes: { ram: "12 GB", storage: "256 GB", display: '6.7"', battery: "5000 mAh" },
    emi: [{ monthly: 1749, tenureMonths: 24 }, { monthly: 3499, tenureMonths: 12 }],
  } as any),
  productSeed(2, {
    slug: "aurora-buds-pro",
    title: "Aurora Buds Pro with ANC",
    brand: "Aurora", brandId: "br-aurora", categoryId: "cat-mob", subcategoryId: "cat-mob-access",
    description: "Active noise cancellation, 38h playback, IPX5 and Hi-Res LDAC audio.",
    highlights: ["Active Noise Cancellation", "38 h total playback", "IPX5 water resistant"],
    price: 2999, mrp: 6999,
    rating: 4.4, ratingCount: 4102, reviewCount: 2890,
    images: [img(201), img(202), img(203)],
    attributes: { type: "In-ear", anc: true, battery: "38 h" },
    fastDelivery: true,
  } as any),
  productSeed(3, {
    slug: "voltrix-tv-55qled",
    title: "Voltrix 55\" QLED 4K Smart TV",
    brand: "Voltrix", brandId: "br-voltrix", categoryId: "cat-elec", subcategoryId: "cat-elec-tv",
    description: "QLED quantum dot panel with Dolby Vision IQ, 60W speakers and a bezel-less design.",
    highlights: ["55\" QLED 4K", "Dolby Vision IQ", "60W Dolby Atmos speakers", "Bezel-less"],
    price: 39999, mrp: 79999,
    rating: 4.5, ratingCount: 1980, reviewCount: 1100,
    images: [img(301), img(302), img(303)],
    attributes: { size: '55"', resolution: "4K", panel: "QLED" },
    emi: [{ monthly: 1666, tenureMonths: 24 }],
  } as any),
  productSeed(4, {
    slug: "lumen-laptop-air-14",
    title: "Lumen Air 14 Laptop (i7, 16GB, 512GB)",
    brand: "Lumen", brandId: "br-lumen", categoryId: "cat-elec", subcategoryId: "cat-elec-laptop",
    description: "Ultralight 1.1 kg chassis, 14\" 2.8K OLED, 12th Gen Intel Core i7 and 16GB LPDDR5.",
    highlights: ["1.1 kg lightweight", "14\" 2.8K OLED", "12th Gen Intel i7", "16GB / 512GB"],
    price: 62999, mrp: 89999,
    rating: 4.7, ratingCount: 1108, reviewCount: 820,
    images: [img(401), img(402), img(403)],
    isNewArrival: true,
    emi: [{ monthly: 2624, tenureMonths: 24 }],
  } as any),
  productSeed(5, {
    slug: "vega-saree-silk-banarasi",
    title: "Vega Banarasi Silk Saree",
    brand: "Vega", brandId: "br-vega", categoryId: "cat-fash", subcategoryId: "cat-fash-women",
    description: "Pure Banarasi silk with intricate zari work. Comes with blouse piece.",
    highlights: ["Pure silk", "Handwoven zari", "Includes blouse piece"],
    price: 2499, mrp: 5999,
    rating: 4.3, ratingCount: 612, reviewCount: 388,
    images: [img(501), img(502)],
    attributes: { fabric: "Silk", color: "Royal Red" },
  } as any),
  productSeed(6, {
    slug: "saffron-kurta-cotton",
    title: "SaffronWear Men's Cotton Kurta",
    brand: "SaffronWear", brandId: "br-saffron", categoryId: "cat-fash", subcategoryId: "cat-fash-men",
    description: "100% cotton straight kurta for festive and casual wear.",
    highlights: ["100% cotton", "Pre-shrunk fabric", "Side slits"],
    price: 899, mrp: 1799,
    rating: 4.1, ratingCount: 320, reviewCount: 220,
    images: [img(601), img(602)],
    attributes: { fabric: "Cotton", fit: "Regular" },
    isFlashDeal: true,
  } as any),
  productSeed(7, {
    slug: "freshkart-atta-10kg",
    title: "FreshKart Chakki Atta 10 kg",
    brand: "FreshKart", brandId: "br-fresh", categoryId: "cat-groc",
    description: "100% whole wheat atta ground in a traditional chakki for soft rotis.",
    highlights: ["100% whole wheat", "Stone-ground", "10 kg pack"],
    price: 399, mrp: 599,
    rating: 4.4, ratingCount: 8200, reviewCount: 6100,
    images: [img(701)],
    attributes: { weight: "10 kg", type: "Whole wheat" },
    fastDelivery: true,
  } as any),
  productSeed(8, {
    slug: "roshni-foundation",
    title: "Roshni Matte Foundation (30ml)",
    brand: "Roshni", brandId: "br-roshni", categoryId: "cat-beau",
    description: "24-hour matte finish, SPF 25, available in 18 shades.",
    highlights: ["24h matte wear", "SPF 25", "18 shades"],
    price: 449, mrp: 799,
    rating: 4.2, ratingCount: 540, reviewCount: 410,
    images: [img(801), img(802)],
    attributes: { shade: "Warm Beige", spf: 25 },
    isFlashDeal: true,
  } as any),
  productSeed(9, {
    slug: "nirmaan-sofa-3s",
    title: "Nirmaan 3-Seater Fabric Sofa",
    brand: "Nirmaan", brandId: "br-nirmaan", categoryId: "cat-home",
    description: "Solid sheesham frame, premium fabric upholstery and pocket spring seating.",
    highlights: ["Sheesham frame", "Pocket spring seating", "Easy assembly"],
    price: 18999, mrp: 34999,
    rating: 4.3, ratingCount: 220, reviewCount: 150,
    images: [img(901), img(902)],
    emi: [{ monthly: 1583, tenureMonths: 12 }],
  } as any),
  productSeed(10, {
    slug: "dhruv-ac-1.5t",
    title: "Dhruv 1.5 Ton 5 Star Inverter AC",
    brand: "Dhruv", brandId: "br-dhruv", categoryId: "cat-app",
    description: "5-star inverter, copper condenser, anti-bacteria filters and turbo cooling.",
    highlights: ["5-star inverter", "Copper condenser", "Turbo cooling"],
    price: 32999, mrp: 48999,
    rating: 4.4, ratingCount: 720, reviewCount: 480,
    images: [img(1001), img(1002)],
    emi: [{ monthly: 1374, tenureMonths: 24 }],
  } as any),
  productSeed(11, {
    slug: "zen-yoga-mat",
    title: "Zen 6mm Anti-Slip Yoga Mat",
    brand: "Zenith", brandId: "br-zen", categoryId: "cat-sport",
    description: "Eco-friendly TPE, 6mm cushioned, anti-slip texture and carry strap.",
    highlights: ["6mm cushion", "Eco-friendly TPE", "Carry strap"],
    price: 599, mrp: 1299,
    rating: 4.5, ratingCount: 410, reviewCount: 280,
    images: [img(1101)],
    fastDelivery: true,
  } as any),
  productSeed(12, {
    slug: "vela-cookbook",
    title: "Vela's Indian Home Cooking",
    brand: "Vela", brandId: "br-vela", categoryId: "cat-books",
    description: "120 traditional Indian recipes by chef Vela Iyer.",
    highlights: ["120 recipes", "Hardcover", "Step-by-step photos"],
    price: 499, mrp: 899,
    rating: 4.7, ratingCount: 188, reviewCount: 122,
    images: [img(1201)],
  } as any),
  productSeed(13, {
    slug: "blocks-wooden-100",
    title: "Blocks Wooden Building Set (100 pcs)",
    brand: "Blocks", brandId: "br-nova", categoryId: "cat-toys",
    description: "100 piece non-toxic wooden building blocks for ages 3+.",
    highlights: ["Non-toxic", "100 pieces", "Ages 3+"],
    price: 799, mrp: 1499,
    rating: 4.6, ratingCount: 312, reviewCount: 240,
    images: [img(1301)],
  } as any),
  productSeed(14, {
    slug: "car-mat-rubber",
    title: "Heavy Duty Rubber Car Floor Mats",
    brand: "Dhruv", brandId: "br-dhruv", categoryId: "cat-auto",
    description: "Universal fit, anti-skid, waterproof rubber car mats.",
    highlights: ["Universal fit", "Anti-skid", "Waterproof"],
    price: 899, mrp: 1999,
    rating: 4.2, ratingCount: 220, reviewCount: 140,
    images: [img(1401)],
    isFlashDeal: true,
  } as any),
  productSeed(15, {
    slug: "watch-classic-leather",
    title: "Classic Leather Analog Watch",
    brand: "Aurora", brandId: "br-aurora", categoryId: "cat-acc",
    description: "Minimalist dial, genuine leather strap, water-resistant 30m.",
    highlights: ["Genuine leather", "30m water resistant", "Japanese movement"],
    price: 1199, mrp: 2999,
    rating: 4.4, ratingCount: 540, reviewCount: 380,
    images: [img(1501)],
  } as any),
  productSeed(16, {
    slug: "novaphone-lite-5g",
    title: "NovaPhone Lite 5G (128 GB)",
    brand: "NovaTech", brandId: "br-nova", categoryId: "cat-mob", subcategoryId: "cat-mob-smart",
    description: "Affordable 5G with 6.4\" AMOLED, 5000 mAh battery, and 48MP camera.",
    highlights: ["5G ready", "5000 mAh battery", "48MP camera"],
    price: 14999, mrp: 21999,
    rating: 4.3, ratingCount: 3200, reviewCount: 2100,
    images: [img(1601), img(1602)],
    attributes: { ram: "6 GB", storage: "128 GB" },
    fastDelivery: true,
  } as any),
  productSeed(17, {
    slug: "voltrix-monitor-27",
    title: "Voltrix 27\" 2K 165Hz Gaming Monitor",
    brand: "Voltrix", brandId: "br-voltrix", categoryId: "cat-elec",
    description: "2K QHD, 165Hz, 1ms response, HDR400 and 99% sRGB.",
    highlights: ["2K 165Hz", "1ms response", "HDR400"],
    price: 19999, mrp: 29999,
    rating: 4.5, ratingCount: 540, reviewCount: 320,
    images: [img(1701)],
    isNewArrival: true,
  } as any),
  productSeed(18, {
    slug: "lumen-band-fit",
    title: "Lumen Fit Smart Band",
    brand: "Lumen", brandId: "br-lumen", categoryId: "cat-mob", subcategoryId: "cat-mob-wear",
    description: "AMOLED display, SpO2, heart rate, 14 day battery.",
    highlights: ["AMOLED display", "SpO2 tracking", "14 day battery"],
    price: 1499, mrp: 2999,
    rating: 4.2, ratingCount: 2100, reviewCount: 1450,
    images: [img(1801)],
    fastDelivery: true,
  } as any),
  productSeed(19, {
    slug: "vega-handbag-tote",
    title: "Vela Faux Leather Tote Handbag",
    brand: "Vela", brandId: "br-vela", categoryId: "cat-fash", subcategoryId: "cat-fash-women",
    description: "Spacious tote with laptop sleeve and inner organizer.",
    highlights: ["Faux leather", "Laptop sleeve", "Inner organizer"],
    price: 1299, mrp: 2999,
    rating: 4.3, ratingCount: 280, reviewCount: 190,
    images: [img(1901)],
  } as any),
  productSeed(20, {
    slug: "freshkart-basmati-5kg",
    title: "FreshKart Premium Basmati Rice 5 kg",
    brand: "FreshKart", brandId: "br-fresh", categoryId: "cat-groc",
    description: "Aged 24 months, extra-long grains, perfect for biryani.",
    highlights: ["Aged 24 months", "Extra long grain", "5 kg pack"],
    price: 699, mrp: 999,
    rating: 4.5, ratingCount: 4200, reviewCount: 3000,
    images: [img(2001)],
    fastDelivery: true,
  } as any),
];

export const banners: Banner[] = [
  {
    id: "bn-1", title: "Festive Electronics Sale",
    subtitle: "Up to 60% off on smartphones & laptops",
    image: img(9001, 1200, 480),
    bg: "from-brand-700 to-brand-950",
    fg: "text-white",
    link: "/category/electronics",
    cta: { label: "Shop now", href: "/category/electronics" },
  },
  {
    id: "bn-2", title: "Fashion Week Special",
    subtitle: "Buy 2 Get 1 Free on selected styles",
    image: img(9002, 1200, 480),
    bg: "from-accent-500 to-accent-700",
    fg: "text-white",
    link: "/category/fashion",
    cta: { label: "Explore fashion", href: "/category/fashion" },
  },
  {
    id: "bn-3", title: "Grocery in 30 minutes",
    subtitle: "Free delivery on first 3 orders",
    image: img(9003, 1200, 480),
    bg: "from-emerald-600 to-emerald-900",
    fg: "text-white",
    link: "/category/grocery",
    cta: { label: "Start shopping", href: "/category/grocery" },
  },
];

export const coupons: Coupon[] = [
  { id: "cp-1", code: "WELCOME10", description: "10% off up to ₹500 on first order", type: "PERCENT", value: 10, maxDiscount: 500, minOrder: 999, appliesTo: "ALL", expiresAt: new Date(Date.now() + 7 * 86400000).toISOString(), usedCount: 0, firstOrderOnly: true },
  { id: "cp-2", code: "LVIGS200", description: "Flat ₹200 off on orders above ₹1499", type: "FLAT", value: 200, minOrder: 1499, appliesTo: "ALL", expiresAt: new Date(Date.now() + 14 * 86400000).toISOString(), usedCount: 0 },
  { id: "cp-3", code: "FESTIVE25", description: "25% off on Electronics", type: "PERCENT", value: 25, maxDiscount: 3000, minOrder: 9999, appliesTo: "CATEGORY", scopeIds: ["cat-elec", "cat-mob"], expiresAt: new Date(Date.now() + 30 * 86400000).toISOString(), usedCount: 0 },
];

export const initialNotifications: NotificationItem[] = [
  { id: "n1", type: "ORDER", title: "Order LVIGS-9081 is out for delivery", body: "Your package will arrive today by 7 PM.", read: false, at: new Date(Date.now() - 3600_000).toISOString(), link: "/orders" },
  { id: "n2", type: "OFFER", title: "Festive Electronics Sale is live", body: "Up to 60% off on smartphones & laptops.", read: false, at: new Date(Date.now() - 86400_000).toISOString(), link: "/category/electronics" },
  { id: "n3", type: "PRICE", title: "Price drop on Aurora Buds Pro", body: "Now ₹2,999 (was ₹6,999).", read: true, at: new Date(Date.now() - 2 * 86400_000).toISOString(), link: "/product/aurora-buds-pro" },
  { id: "n4", type: "STOCK", title: "Back in stock: Lumen Air 14", body: "The laptop you wishlisted is available now.", read: true, at: new Date(Date.now() - 3 * 86400_000).toISOString(), link: "/product/lumen-laptop-air-14" },
];

const sampleAddress: Address = {
  id: "addr-1", label: "HOME", name: "Gopal Krishna",
  mobile: "9876543210",
  pincode: "560001",
  line1: "12, 2nd Floor, MG Road",
  line2: "Near Trinity Metro Station",
  landmark: "Opposite City Mall",
  city: "Bengaluru",
  state: "Karnataka",
  country: "India",
  isDefault: true,
};

export const sampleOrders: Order[] = [
  {
    id: "ord-1",
    shortId: "LVIGS-9081",
    userId: "u-1",
    items: [
      { id: "oi-1", productId: "pr-1", title: "NovaPhone X9 Pro 5G", image: img(101), quantity: 1, price: 34999, mrp: 54999, status: "OUT_FOR_DELIVERY" },
    ],
    address: sampleAddress,
    payment: { method: "UPI", status: "SUCCESS", transactionId: "pay_Nf8sd0c1q" },
    totals: {
      itemCount: 1, mrpTotal: 54999, priceTotal: 34999, itemDiscount: 20000,
      couponDiscount: 0, deliveryFee: 0, freeDelivery: true, tax: 0,
      payable: 34999, savings: 20000,
    },
    status: "OUT_FOR_DELIVERY",
    timeline: [
      { status: "PLACED", at: new Date(Date.now() - 4 * 86400_000).toISOString() },
      { status: "CONFIRMED", at: new Date(Date.now() - 4 * 86400_000 + 60_000).toISOString() },
      { status: "PACKED", at: new Date(Date.now() - 3 * 86400_000).toISOString() },
      { status: "SHIPPED", at: new Date(Date.now() - 1 * 86400_000).toISOString() },
      { status: "OUT_FOR_DELIVERY", at: new Date(Date.now() - 2 * 3600_000).toISOString() },
    ],
    expectedDelivery: new Date(Date.now() + 8 * 3600_000).toISOString(),
    trackingId: "LVGS-TRK-9081",
    deliveryPartner: { name: "Ravi Kumar", mobile: "+91 90000 12345", rating: 4.8 },
    createdAt: new Date(Date.now() - 4 * 86400_000).toISOString(),
  },
  {
    id: "ord-2",
    shortId: "LVIGS-9042",
    userId: "u-1",
    items: [
      { id: "oi-2", productId: "pr-7", title: "FreshKart Chakki Atta 10 kg", image: img(701), quantity: 1, price: 399, mrp: 599, status: "DELIVERED" },
    ],
    address: sampleAddress,
    payment: { method: "COD", status: "SUCCESS" },
    totals: {
      itemCount: 1, mrpTotal: 599, priceTotal: 399, itemDiscount: 200,
      couponDiscount: 0, deliveryFee: 0, freeDelivery: true, tax: 0,
      payable: 399, savings: 200,
    },
    status: "DELIVERED",
    timeline: [
      { status: "PLACED", at: new Date(Date.now() - 14 * 86400_000).toISOString() },
      { status: "CONFIRMED", at: new Date(Date.now() - 14 * 86400_000 + 60_000).toISOString() },
      { status: "PACKED", at: new Date(Date.now() - 13 * 86400_000).toISOString() },
      { status: "SHIPPED", at: new Date(Date.now() - 12 * 86400_000).toISOString() },
      { status: "OUT_FOR_DELIVERY", at: new Date(Date.now() - 11 * 86400_000).toISOString() },
      { status: "DELIVERED", at: new Date(Date.now() - 11 * 86400_000 + 60_000).toISOString(), note: "Delivered to recipient" },
    ],
    expectedDelivery: new Date(Date.now() - 11 * 86400_000).toISOString(),
    deliveredAt: new Date(Date.now() - 11 * 86400_000 + 60_000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 86400_000).toISOString(),
  },
];

export const sampleReviews: Review[] = [
  { id: "rv-1", productId: "pr-1", userId: "u-99", userName: "Anita P.", rating: 5, title: "Excellent phone", body: "Camera quality is outstanding. Battery easily lasts a day and a half.", images: [img(1101)], verified: true, helpful: 142, createdAt: new Date(Date.now() - 8 * 86400_000).toISOString() },
  { id: "rv-2", productId: "pr-1", userId: "u-98", userName: "Sandeep K.", rating: 4, title: "Great value", body: "Performance is great for the price. Speakers are loud and clear.", images: [], verified: true, helpful: 56, createdAt: new Date(Date.now() - 12 * 86400_000).toISOString() },
  { id: "rv-3", productId: "pr-1", userId: "u-97", userName: "Riya M.", rating: 5, title: "Loved it", body: "The display is gorgeous. Gaming performance is top notch.", images: [img(1201)], verified: true, helpful: 31, createdAt: new Date(Date.now() - 20 * 86400_000).toISOString() },
];